"""empty message

Revision ID: 3397ca048fb9
Revises: 
Create Date: 2023-09-11 17:24:59.847424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3397ca048fb9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wallet_balance', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('overall_earning', sa.Integer(), nullable=True))
        batch_op.alter_column('overall_referals',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('overall_deposit',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('overall_deposit',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('overall_referals',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('overall_earning')
        batch_op.drop_column('wallet_balance')

    # ### end Alembic commands ###
