"""empty message

Revision ID: 35dd7857597c
Revises: d56842ae0c81
Create Date: 2023-09-22 12:27:50.214999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35dd7857597c'
down_revision = 'd56842ae0c81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('today_earning', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('monthly_earning', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('monthly_earning')
        batch_op.drop_column('today_earning')

    # ### end Alembic commands ###
