"""empty message

Revision ID: 389160fae09a
Revises: 9ad90851a8d6
Create Date: 2023-09-24 12:11:46.532820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '389160fae09a'
down_revision = '9ad90851a8d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('no_of_tickets', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.drop_column('no_of_tickets')

    # ### end Alembic commands ###
