"""empty message

Revision ID: 8570ffcc7f00
Revises: e3817c6f7337
Create Date: 2023-09-30 15:11:34.878082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8570ffcc7f00'
down_revision = 'e3817c6f7337'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_resquests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_resquests', schema=None) as batch_op:
        batch_op.drop_column('amount')

    # ### end Alembic commands ###
