"""empty message

Revision ID: 9ad90851a8d6
Revises: 35dd7857597c
Create Date: 2023-09-22 12:31:47.068891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ad90851a8d6'
down_revision = '35dd7857597c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('today_earning',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('monthly_earning',
               existing_type=sa.FLOAT(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('monthly_earning',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('today_earning',
               existing_type=sa.FLOAT(),
               nullable=True)

    # ### end Alembic commands ###
