"""empty message

Revision ID: b274ec89f8e5
Revises: 3397ca048fb9
Create Date: 2023-09-11 17:29:28.726675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b274ec89f8e5'
down_revision = '3397ca048fb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('overall_earning',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('overall_earning',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
