"""empty message

Revision ID: d56842ae0c81
Revises: 9e1d6fd21c90
Create Date: 2023-09-15 18:22:08.416872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd56842ae0c81'
down_revision = '9e1d6fd21c90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('purchased_tickets', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('purchased_tickets')

    # ### end Alembic commands ###
